### ISSUE TITLE
add extended trim

### ISSUE THREAD

**Issue by olegbaturin** [yiisoft/strings#104]
```
public static function trim(string $str): string
{
    return trim($str, " \t\n\r\0\x0B\xC2\xA0\xEF\xBB\xBF");
}

```

**Comment by vjik** [comment]
In what cases is this necessary?

**Comment by olegbaturin** [comment]
> In what cases is this necessary?

I'm using it to sanitize user input data.

**Comment by samdark** [comment]
Sanitize it from what exactly? Why exactly this characters set but not, for example, `x0c`?

**Comment by olegbaturin** [comment]
Updated method for advanced trimming ascii and utf8 strings
```
public static function trim(string $str): string
{
    return preg_replace("#^[\pC\pZ]+|[\pC\pZ]+$#u", '', $str);
}
```

List of unicode whitespace characters https://en.wikipedia.org/wiki/Whitespace_character#Unicode

**Comment by vjik** [comment]
1) Which is faster: `trim()` with full symbols list or `preg_replace()`

2) Should this method has name `trim` or more specific?

**Comment by olegbaturin** [comment]
1. trim() removes only single bytes specified in $characters parameter and can't safely remove multibyte characters.
2. When PCRE modifier u(PCRE_UTF8) is set, strings are treated as UTF-8, so it's a utf8 trim.

Generalized version
```
public static function trim(string $str, string $pattern = "\pC\pZ"): string
{
    return preg_replace("#^[$pattern]+|[$pattern]+$#u", '', $str);
}
```

**Comment by vjik** [comment]
I think need use another name... May be:

- `regexpTrim()` (I like it)
- `pregTrim()`
- `reTrim()`

?

**Comment by olegbaturin** [comment]
> I think need use another name... May be:
> 
>     * `regexpTrim()` (I like it)
> 
>     * `pregTrim()`
> 
>     * `reTrim()`
> 
> 
> ?
> 
> But I not sure. May be `trim` better name =) Need more opinions.

trim() is well known function name for string trimming. Does the implementation details matter?

**Comment by vjik** [comment]
@olegbaturin Will you undertake to do PR?

**Comment by olegbaturin** [comment]
What about ltrim()/rtrim()?

**Comment by xepozz** [comment]
> > I think need use another name... May be:
> > ```
> > * `regexpTrim()` (I like it)
> > 
> > * `pregTrim()`
> > 
> > * `reTrim()`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ?
> > But I not sure. May be `trim` better name =) Need more opinions.
> 
> trim() is well known function name for string trimming. Does the implementation details matter?

The implementations matter when performance is a goal, but otherwise developers may use regular `trim`, so it's good to have kind of boosted `trim`

**Comment by olegbaturin** [comment]
> developers may use regular `trim`

Regular `trim` can't be used to remove unicode symbols, unfortunately.

**Comment by xepozz** [comment]
So would you like to implement it?

**Comment by xepozz** [comment]
I think all `trim`, `ltrim`, `rtrim` can be here.

**Comment by vjik** [comment]
Done by #109
