### ISSUE TITLE
Two files into separate package?

### ISSUE THREAD

**Issue by lubosdz** [yiisoft/strings#11]
Why loading helpers as separate package - ? It's just two files .. 
Will all helpers become separate packages now ? - ArrayHelper, FileHelper, ... ?

Is it to allow standalone usages for non Yii-framework folks?
It looks again like mimicking the symfony way - just to collect downloading statistics ...

**Comment by samdark** [comment]
> Why loading helpers as separate package - ? It's just two files ..
> Is it to allow standalone usages for non Yii-framework folks?

Because they're handy and are used in different packages, including non-Yii, where all files aren't necessary.

> Will all helpers become separate packages now ? - ArrayHelper, FileHelper, ... ?

Mostly yes.
