### ISSUE TITLE
truncate begin

### ISSUE THREAD

**Issue by kamarton** [yiisoft/strings#18]
`StringHelper::truncateBegin()` function to cut off the beginning of text content.

use case:
```php
// sms sent to …234.
echo 'sms sent to ' . StringHelper::truncateBegin($model->phone, 3). '.';
```

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by mapeveri** [comment]
I sent a PR related to this issue :)
