### ISSUE TITLE
truncateMiddle improvements

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/strings#27]
I think [truncateMiddle](#25) function (also `truncateBegin` and `truncateCharacters`) should have a different behavior.

We need to set the limit of the total string length, which includes the length of the separator.
For example:
original string `0123456789`
```
truncateMiddle ('123456789', 8, '...');
```
As a result, we should get `123...89` or `12...789`, and not `1234...6789` (11 symbols)

~~I also think that the function should first crop whitespace from the edges, and only then cut the content from the middle if necessary~~

**Comment by machour** [comment]
I think that the function is good as it is. With your proposal:

1. what would this return ?
`truncateMiddle ('123456789', 3, '...');`

2. what if I do want to keep the whitespaces? You can use trim() on your side

**Comment by roxblnfk** [comment]
1 Invalid argument exception
2 ok

**Comment by samdark** [comment]
It should be consistent with other trim methods.

**Comment by roxblnfk** [comment]
> It should be consistent with other trim methods.

Of course, this also applies to other methods.

**Comment by samdark** [comment]
I find this idea suitable. Usually when trimming a string the goal is to reduce it to a certain number of characters.

**Comment by kamarton** [comment]
> I find this idea suitable. Usually when trimming a string the goal is to reduce it to a certain number of characters.

By default, the length of `$separator` should be counted, then which is often difficult. For example: last N digits of phone, bank card, contact number.

It makes sense when displaying with with a monospace font, but usually the purpose in the browser  is "don't be too long text".

What do you think of the `$includeSeparator = false` function parameter.

**Comment by samdark** [comment]
> What do you think of the $includeSeparator = false function parameter.

I'm against having it so either changing behavior by default or not changing it. Both are OK.

**Comment by yiiliveext** [comment]
I think it would be better to create a separate `function truncateMonospace($data, $resultLength, $separator, $separatorPosition)` for fixed|monospace text such as phone numbers, bank cards numbers etc.
