### ISSUE TITLE
New methods reverse and containsAny

### ISSUE THREAD

**Issue by mapeveri** [yiisoft/strings#28]
What do you think about this two new methods?

```
StringHelper::containsAny('aeiou', 'a');  // true
StringHelper::containsAny('aeiou', ['ab', 'efg']); // false
StringHelper::containsAny('aeiou', ['eio', 'foo', 'z']); // true
```

And 

`StringHelper::reverse('foo bar'); // 'rab oof'`

If they agree, I could send a PR.

**Comment by samdark** [comment]
What are use cases for these?

**Comment by mapeveri** [comment]
The first case, It happened to me that I had to check if a string contains a character. This would help a lot.

The second case, For many cases, regular expressions, multi language support (for languages that use letters right-to-left), etc.

**Comment by samdark** [comment]
Both are PHP built-in functions:

- https://www.php.net/manual/en/function.strpbrk.php
- https://www.php.net/manual/en/function.strrev.php
