### ISSUE TITLE
Change namespace to Yiisoft\Strings

### ISSUE THREAD

**Issue by samdark** [yiisoft/strings#4]
I think we need to change namespace to Yii\Strings. That would allow us adding more classes to the package that won't be helpers.

**Comment by machour** [comment]
Agreed & done.

Could you rename this repo to `strings` ? I also changed the composer package name to `yiisoft/strings`

**Comment by machour** [comment]
Package should be republished to packagist using the new name too.

**Comment by samdark** [comment]
Done.
