### ISSUE TITLE
Add method for implode array with callable

### ISSUE THREAD

**Issue by vjik** [yiisoft/strings#82]
For example:

```php
$result = $separator = '';
foreach ($items as $item) {
    $result .= $separator . $toString($item);
    $separator = ', ';
}
```

or 

```php
implode(', ', array_map(fn => ..., $array));
```

Method should take `iterable<string>`.

Idea from:
- https://t.me/leonidchernenko/7227,
- https://t.me/leonidchernenko/7228,
- https://t.me/leonidchernenko/7252.

**Comment by xepozz** [comment]
Also good idea for applying some case manipulations with a list of words, e.g. `$inflector->toCamelCase(['test', 'sum'])` -> `testSum`

**Comment by vjik** [comment]
Decided not to implement it. 

This is OK:

```php
implode(', ', array_map(fn => ..., $array));
```
